// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhvQqFLZMJ415G20LtncIVe96ME58rqU8',
    appId: '1:397204010510:web:831758ea8cb44eb8702e5f',
    messagingSenderId: '397204010510',
    projectId: 'ams-employees',
    authDomain: 'ams-employees.firebaseapp.com',
    storageBucket: 'ams-employees.appspot.com',
    measurementId: 'G-ET76DV9QK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB03kXcJNf-4eXw99JxmnUCKmIx0VrzThM',
    appId: '1:397204010510:android:461b8036dbcfd30c702e5f',
    messagingSenderId: '397204010510',
    projectId: 'ams-employees',
    storageBucket: 'ams-employees.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYwE9GxCwp5laCbdX99R13-L3kP1uLMOw',
    appId: '1:397204010510:ios:8062246f15994a66702e5f',
    messagingSenderId: '397204010510',
    projectId: 'ams-employees',
    storageBucket: 'ams-employees.appspot.com',
    iosClientId: '397204010510-7bdtlidb1gvohbeddlbdlv8cfhdcu5nt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whiteboxAms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYwE9GxCwp5laCbdX99R13-L3kP1uLMOw',
    appId: '1:397204010510:ios:3980e5fd4ebbfe36702e5f',
    messagingSenderId: '397204010510',
    projectId: 'ams-employees',
    storageBucket: 'ams-employees.appspot.com',
    iosClientId: '397204010510-d4el3k7888ar0jg076q381hbj24ppn43.apps.googleusercontent.com',
    iosBundleId: 'com.example.whiteboxAms.RunnerTests',
  );
}
